# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Prayerandpraise:
  fields:
    list: title, email, published
    form: title, email, body, published
  order_by: 
  relationships: 
  filters: 
  search: 
  application: temple_rails

