# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

WedNightSupper:
  fields:
    list: meal, date, published
    form: meal, date, published
  order_by: 
  relationships: 
  filters: 
  search: 
  application: temple_rails

