# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Blog:
  fields:
    list: title, published
    form: title, body, published
  order_by: 
  relationships: 
  filters: 
  search: 
  application: temple_rails

