# Controller generated by the `typus_watch_dog` generator.
class Admin::WatchDogController < TypusController

  def index
    @crontab = `crontab -l`
    @application_log = `tail -25 #{Rails.root}/log/#{Rails.env}.log`
  end

end